language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t elokazy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true elokazy/docker-react npm run test 